# Generated by Django 3.0.5 on 2020-04-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(blank=True, choices=[('S', 'Седан'), ('U', 'Универсал'), ('V', 'Внедорожник'), ('K', 'Кроссовер'), ('H', 'Хэтчбэк'), ('N', 'None')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, choices=[('Б', 'Бензин'), ('Д', 'Дизель'), ('Э', 'Электро'), ('N', 'None')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField()),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carSale.BodyType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carSale.Company')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carSale.EngineType')),
            ],
        ),
    ]
