# Generated by Django 3.0.5 on 2020-04-28 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(blank=True, choices=[('Седан', 'Седан'), ('Универсал', 'Универсал'), ('Внедорожник', 'Внедорожник'), ('Кроссовер', 'Кроссовер'), ('Хэтчбэк', 'Хэтчбэк'), ('None', 'None')], default='N', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(blank=True, choices=[('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электро', 'Электро'), ('None', 'None')], default='N', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.IntegerField(null=True)),
                ('year', models.DateField(null=True)),
                ('mileage', models.IntegerField()),
                ('engine_volume', models.FloatField()),
                ('phone_number', models.CharField(max_length=19)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carSale.BodyType')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carSale.Company')),
                ('engine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carSale.EngineType')),
            ],
        ),
    ]
