# Generated by Django 3.0.5 on 2020-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carSale', '0003_remove_mail_check_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='check_send',
            field=models.BooleanField(default=False),
        ),
    ]
