# Generated by Django 3.0.5 on 2020-05-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carSale', '0004_mail_check_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='check_send',
            new_name='posted',
        ),
    ]
